### PR TITLE
Provide additional ctx for RenderToken

### PR DESCRIPTION
**Pull request by revskill10**
We should provide additional `ctx` for the custom renderer could have additional control logic.

### CODE REVIEW

**Comment by revskill10** [comment]
Close due to merging with #285

**Comment by lhorie** [comment]
I actually feel like this could/should be looked at separately from #285, which is a bigger change

**Comment by lhorie** [comment]
Rationale: non-react view libraries might not expose a context-like API, so there needs to be some way of determining request data from render for e.g. routing purposes. Custom renderers may also need to have access to ctx for various reasons (e.g. streaming rendering)

**Comment by revskill10** [comment]
@lhorie Could you give me one example of that use case when we need to check ?

**Pull request merged**
